#!/usr/bin/env bash
# This script displays the username, user id, and home directory path for each user in /etc/passwd

while IFS=":" read -r username _ userid _ homedir _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < /etc/passwd
