#!/usr/bin/env bash
# This script displays the content of /etc/passwd using a while loop and IFS

while IFS=: read -r username gid gang home_directory command shell passwd info
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. User ID's place is protected by the passcode %s, more info about the user here: %s\n" "$username" "$gid" "$gang" "$home_directory" "$passwd" "$info"
done < /etc/passwd
