#!/usr/bin/env bash
# This script tells a fictional story based on the content of /etc/passwd

while IFS=":" read -r username _ userid groupid _ homedir shell; do
    passcode=$(grep "^$username:" /etc/shadow | cut -d':' -f2)
    user_info=$(finger -m "$username" | awk -F: 'NR==1{print $3}')

    echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd
