#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data sorted by the number of occurrences

awk '{print $1, $9}' apache-access.log | sort | uniq -c | awk '{print $1, $3, $2}' | sort -nr
