#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

hour=0
minute=1
while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" "$hour" "$minute"
        minute=$((minute + 1))
        if [ $minute -eq 60 ]; then
            minute=0
            break
        fi
    done
    hour=$((hour + 1))
done | head -n 70
