#!/usr/bin/env bash
# This script displays the time from 00:01 to 12:59

h=0
while [ "$h" -le 12 ]
do
    echo "Hour: $h"
    (( h++ ))

    m=1
    while [ "$m" -le 59 ]
    do
	echo "$m"
	(( m++ ))
    done
done
