#!/usr/bin/env bash
# This script displays the time from 00:01 to 12:59

hours=0
minutes=1

while [ $hours -le 12 ] && [ $minutes -le 59 ]
do
    printf "%02d:%02d\n" $hours $minutes
    if [ $minutes -eq 59 ]
    then
        minutes=0
        hours=$((hours+1))
    else
        minutes=$((minutes+1))
    fi
done | head -n 70
